apiVersion: apps/v1
kind: Deployment
metadata:
  name: maua-ecm516-lembretes-deployment
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: maua-ecm516-lembretes-deployment
  template: 
    metadata:
      labels:
        app: maua-ecm516-lembretes-deployment
    spec:
      containers:
        - name: maua-ecm516-lembretes-deployment
          image: rodbossini/maua-ecm516-lembretes
          resources:
            limits:
              memory: 256Mi
              cpu: "1" 