apiVersion: v1
kind: Service
metadata:
    name: maua-ecm516-lembretes-service
spec:
  type: NodePort
  selector:
    app: maua-ecm516-lembretes-deployment
  ports:
      - name: maua-ecm516-lembretes-service
        protocol: TCP
        port: 4000
        targetPort: 4000